name: png_chunks_extract
description: Extract the data chunks from a PNG file.
  Useful for reading the metadata of a PNG image, or as the base of a more complete PNG parser.
version: 1.0.2
homepage: https://github.com/FlutterFans/png_chunks_extract

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
